<?php

namespace App\Console\Commands;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\InformationController;
use Illuminate\Console\Attributes\Description;
use Illuminate\Console\Attributes\Signature;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\URL;

#[Signature('site:export {--output= : Override the generated output directory}')]
#[Description('Export the public Golden Hair pages and assets as a static site served by Vercel')]
class ExportStaticSite extends Command
{
    public function handle(): int
    {
        if (File::exists(public_path('hot')) || ! File::exists(public_path('build/manifest.json'))) {
            $this->error('Run npm run build and stop the Vite development server before exporting.');

            return self::FAILURE;
        }

        $output = $this->option('output') ?: base_path('dist');
        $marker = $output.'/.goldenhair-static-export';
        if (File::isDirectory($output) && ! File::exists($marker) && count(File::allFiles($output, true)) > 0) {
            $this->error('The output directory contains files that were not generated by this command.');

            return self::FAILURE;
        }

        $origin = 'https://goldenhair-export.invalid';
        URL::useOrigin($origin);
        URL::useAssetOrigin($origin);
        URL::forceScheme('https');

        try {
            $pages = [
                'index.html' => app(HomeController::class)->index()->render(),
                'mentions-legales.html' => app(InformationController::class)->legal()->render(),
                'confidentialite.html' => app(InformationController::class)->privacy()->render(),
                '404.html' => view('errors.404', ['business' => config('business')])->render(),
            ];
        } finally {
            URL::useOrigin(null);
            URL::useAssetOrigin(config('app.asset_url'));
            URL::forceScheme(null);
        }

        File::deleteDirectory($output);
        File::ensureDirectoryExists($output);
        File::put($marker, "Generated by php artisan site:export\n");

        foreach ($pages as $name => $html) {
            File::put($output.'/'.$name, str_replace([$origin.'/', $origin], ['/', '/'], $html));
        }

        foreach (['images', 'build'] as $directory) {
            foreach (File::allFiles(public_path($directory)) as $file) {
                if (! in_array(strtolower($file->getExtension()), ['jpg', 'jpeg', 'png', 'webp', 'avif', 'svg', 'ico', 'css', 'js', 'woff', 'woff2'], true)) {
                    continue;
                }

                $destination = $output.'/'.$directory.'/'.$file->getRelativePathname();
                File::ensureDirectoryExists(dirname($destination));
                File::copy($file->getPathname(), $destination);
            }
        }

        File::copy(public_path('robots.txt'), $output.'/robots.txt');

        $this->info('Exported 3 public pages, a 404 page, and public assets to '.$output);

        return self::SUCCESS;
    }
}
