<?php

namespace App\Console\Commands;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\InformationController;
use Illuminate\Console\Attributes\Description;
use Illuminate\Console\Attributes\Signature;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\URL;
use Symfony\Component\Finder\SplFileInfo;

#[Signature('site:export {--output= : Override the generated output directory} {--check : Verify that the existing export matches a fresh one instead of writing it}')]
#[Description('Export the public Golden Hair pages and assets as a static site served by Vercel')]
class ExportStaticSite extends Command
{
    private const ORIGIN = 'https://goldenhair-export.invalid';

    public function handle(): int
    {
        if (File::exists(public_path('hot')) || ! File::exists(public_path('build/manifest.json'))) {
            $this->error('Run npm run build and stop the Vite development server before exporting.');

            return self::FAILURE;
        }

        $output = $this->option('output') ?: base_path('dist');

        if ($this->option('check')) {
            return $this->check($output);
        }

        if (File::isDirectory($output) && ! File::exists($output.'/.goldenhair-static-export') && count(File::allFiles($output, true)) > 0) {
            $this->error('The output directory contains files that were not generated by this command.');

            return self::FAILURE;
        }

        $this->generate($output);
        $this->info('Exported 3 public pages, a 404 page, and public assets to '.$output);

        return self::SUCCESS;
    }

    /**
     * Render a fresh export in a temporary directory and compare it with the existing one.
     */
    private function check(string $output): int
    {
        if (! File::isDirectory($output)) {
            $this->error('No export found at '.$output.'. Run npm run build:static.');

            return self::FAILURE;
        }

        $fresh = storage_path('framework/cache/static-export-'.uniqid());

        try {
            $this->generate($fresh);
            $differences = $this->differences($fresh, $output);
        } finally {
            File::deleteDirectory($fresh);
        }

        if ($differences === []) {
            $this->info('The static export is up to date.');

            return self::SUCCESS;
        }

        $this->error('The static export is out of date. Run npm run build:static and commit the result.');
        foreach (array_slice($differences, 0, 15) as $difference) {
            $this->line(' - '.$difference);
        }
        if (count($differences) > 15) {
            $this->line(' - ... and '.(count($differences) - 15).' more');
        }

        return self::FAILURE;
    }

    private function generate(string $output): void
    {
        URL::useOrigin(self::ORIGIN);
        URL::useAssetOrigin(self::ORIGIN);
        URL::forceScheme('https');

        try {
            $pages = [
                'index.html' => app(HomeController::class)->index()->render(),
                'mentions-legales.html' => app(InformationController::class)->legal()->render(),
                'confidentialite.html' => app(InformationController::class)->privacy()->render(),
                '404.html' => view('errors.404', ['business' => config('business')])->render(),
            ];
        } finally {
            URL::useOrigin(null);
            URL::useAssetOrigin(config('app.asset_url'));
            URL::forceScheme(null);
        }

        File::deleteDirectory($output);
        File::ensureDirectoryExists($output);
        File::put($output.'/.goldenhair-static-export', "Generated by php artisan site:export\n");

        foreach ($pages as $name => $html) {
            File::put($output.'/'.$name, str_replace([self::ORIGIN.'/', self::ORIGIN], ['/', '/'], $html));
        }

        foreach (['images', 'build'] as $directory) {
            foreach (File::allFiles(public_path($directory)) as $file) {
                if (! in_array(strtolower($file->getExtension()), ['jpg', 'jpeg', 'png', 'webp', 'avif', 'svg', 'ico', 'css', 'js', 'woff', 'woff2'], true)) {
                    continue;
                }

                $destination = $output.'/'.$directory.'/'.$file->getRelativePathname();
                File::ensureDirectoryExists(dirname($destination));
                File::copy($file->getPathname(), $destination);
            }
        }

        File::copy(public_path('robots.txt'), $output.'/robots.txt');
    }

    /**
     * @return list<string>
     */
    private function differences(string $expected, string $actual): array
    {
        $index = fn (string $root): array => collect(File::allFiles($root, true))
            ->mapWithKeys(fn (SplFileInfo $file): array => [str_replace('\\', '/', $file->getRelativePathname()) => sha1_file($file->getPathname())])
            ->sortKeys()
            ->all();

        $expectedFiles = $index($expected);
        $actualFiles = $index($actual);
        $differences = [];

        foreach ($expectedFiles as $path => $hash) {
            if (! isset($actualFiles[$path])) {
                $differences[] = 'missing: '.$path;
            } elseif ($actualFiles[$path] !== $hash) {
                $differences[] = 'changed: '.$path;
            }
        }

        foreach (array_keys(array_diff_key($actualFiles, $expectedFiles)) as $path) {
            $differences[] = 'obsolete: '.$path;
        }

        return $differences;
    }
}
