<?php

return [
    'name' => 'GOLDEN HAIR',
    'description' => 'GOLDEN HAIR — Coiffure • Barber au Lamentin, Martinique. Découvrez nos prestations, produits et coordonnées.',
    'activity' => 'Coiffure • Barber',
    'tagline' => 'Coiffure • Barber · Le Lamentin',
    'intro' => 'Coiffures, coupes, soins et entretien des locks pour femmes, hommes et enfants, au cœur du Lamentin.',
    'logo' => 'images/branding/golden-hair-logo.webp',
    'site_url' => env('SITE_URL'),
    'share_image' => 'images/branding/og-image.jpg',
    'hero_photo' => [
        'src' => 'images/business/salon-banner.webp',
        'alt' => 'Visuel Golden Hair, coiffure et barber au Lamentin',
    ],
    'photos' => [
    ],
    'contact' => [
        'address' => '22 Place Emile Berlan',
        'postal_city' => '97232 LE LAMENTIN, Martinique',
        'address_confirmed' => true,
        'phone' => '+596 696 97 64 78',
        'phone_confirmed' => true,
        'whatsapp' => '+596 696 18 08 34',
        'email' => 'goldenhair.martinique@gmail.com',
        'instagram' => 'https://www.instagram.com/goldenhair.martinique/',
        'instagram_label' => '@goldenhair.martinique',
    ],
    'hours_summary' => 'Du lundi au samedi · 8h30 – 17h00',
    'hours' => [
        ['day' => 'Lundi', 'hours' => '8h30 – 17h00', 'schema_day' => 'Monday', 'opens' => '08:30', 'closes' => '17:00'],
        ['day' => 'Mardi', 'hours' => '8h30 – 17h00', 'schema_day' => 'Tuesday', 'opens' => '08:30', 'closes' => '17:00'],
        ['day' => 'Mercredi', 'hours' => '8h30 – 17h00', 'schema_day' => 'Wednesday', 'opens' => '08:30', 'closes' => '17:00'],
        ['day' => 'Jeudi', 'hours' => '8h30 – 17h00', 'schema_day' => 'Thursday', 'opens' => '08:30', 'closes' => '17:00'],
        ['day' => 'Vendredi', 'hours' => '8h30 – 17h00', 'schema_day' => 'Friday', 'opens' => '08:30', 'closes' => '17:00'],
        ['day' => 'Samedi', 'hours' => '8h30 – 17h00', 'schema_day' => 'Saturday', 'opens' => '08:30', 'closes' => '17:00'],
        ['day' => 'Dimanche', 'hours' => 'Fermé'],
    ],
    'services' => [
        [
            'category' => 'Tresses',
            'name' => 'Tresses plaquées avec dégradé',
            'description' => 'Des tresses fines et épaisses se dessinent sur le dessus, avec des côtés dégradés et des contours précis.',
            'photo' => ['src' => 'images/services/tresses-plaquees-degrade.jpg', 'alt' => 'Tresses plaquées alternant fines et grosses nattes, vues du dessus'],
            'alternate_photos' => [['src' => 'images/services/tresses-plaquees-degrade-profil.jpg', 'alt' => 'Vue de profil des tresses plaquées et du dégradé autour des tempes']],
        ],
        [
            'category' => 'Coupe',
            'name' => 'Boucles & dégradé bas',
            'description' => 'Du volume et des boucles définies sur le dessus, associés à un dégradé bas et à une finition nette aux tempes.',
            'photo' => ['src' => 'images/services/boucles-degrade-bas.jpg', 'alt' => 'Coupe bouclée avec dégradé bas et contours nets'],
            'alternate_photos' => [['src' => 'images/services/boucles-degrade-bas-profil.jpg', 'alt' => 'Autre profil de la coupe bouclée avec dégradé bas']],
        ],
        [
            'category' => 'Locks',
            'name' => 'Chignon de locks en pétales',
            'description' => 'Des locks relevées et repliées en boucles pour composer un chignon sculpté, avec du volume et un mouvement sur le côté.',
            'photo' => ['src' => 'images/services/chignon-locks-petales.jpg', 'alt' => 'Locks relevées en chignon avec des boucles en forme de pétales'],
        ],
        [
            'category' => 'Coupe & motifs',
            'name' => 'Dégradé à motifs graphiques',
            'description' => 'Un dessus court et texturé, souligné par des motifs rasés qui se prolongent sur le côté et à l’arrière de la tête.',
            'photo' => ['src' => 'images/services/degrade-motifs-graphiques.jpg', 'alt' => 'Coupe courte bouclée avec motifs graphiques rasés sur le côté'],
        ],
        [
            'category' => 'Coupe',
            'name' => 'Dégradé & coiffage vers l’arrière',
            'description' => 'Des côtés courts fondus progressivement dans un dessus plus long, coiffé vers l’arrière avec un léger mouvement de côté.',
            'photo' => ['src' => 'images/services/degrade-coiffage-arriere.jpg', 'alt' => 'Dégradé progressif avec dessus plus long coiffé vers l’arrière'],
        ],
        [
            'category' => 'Coupe & coloration',
            'name' => 'Boucles bordeaux',
            'description' => 'Une coupe courte aux boucles généreuses, avec des côtés affinés et des reflets bordeaux qui mettent la texture en valeur.',
            'photo' => ['src' => 'images/services/boucles-bordeaux.jpg', 'alt' => 'Coupe courte bouclée de couleur bordeaux avec côtés plus courts'],
        ],
        [
            'category' => 'Locks',
            'name' => 'Demi-attache de locks en pétales',
            'description' => 'Des boucles de locks assemblées en hauteur, tandis que les longueurs du dessous restent libres pour une silhouette pleine de mouvement.',
            'photo' => ['src' => 'images/services/demi-attache-locks-petales.jpg', 'alt' => 'Locks en demi-attache avec boucles décoratives en hauteur et longueurs libres'],
        ],
        [
            'category' => 'Torsades',
            'name' => 'Fines torsades à pointes libres',
            'description' => 'De fines mèches torsadées encadrent la tête. Les pointes libres conservent une texture souple et donnent du volume aux longueurs.',
            'photo' => ['src' => 'images/services/torsades-pointes-libres.jpg', 'alt' => 'Fines torsades avec des pointes libres et texturées'],
        ],
        [
            'category' => 'Tresses fines',
            'name' => 'Microtresses à pointes libres',
            'description' => 'De très fines mèches travaillées sur de petites sections régulières, avec des longueurs légères et des pointes laissées libres.',
            'photo' => ['src' => 'images/services/microtresses-pointes-libres.jpg', 'alt' => 'Vue rapprochée des fines mèches et de leurs séparations aux racines'],
        ],
        [
            'category' => 'En cours de réalisation',
            'name' => 'Microtresses, pas à pas',
            'description' => 'Un aperçu du travail de précision : les petites sections sont séparées et regroupées au fil de la réalisation de la coiffure.',
            'photo' => ['src' => 'images/services/microtresses-realisation.jpg', 'alt' => 'Coiffure en cours avec fines tresses regroupées par sections et cheveux libres sur le dessus'],
        ],
    ],
    'price_groups' => [
        [
            'title' => 'Coiffures & coupes',
            'items' => [
                [
                    'name' => 'Tresses demi-tête',
                    'price' => '25 €',
                ],
                [
                    'name' => 'Twist demi-tête 1 brin',
                    'price' => '15 €',
                ],
                [
                    'name' => 'Twist demi-tête 2 brins',
                    'price' => '20 €',
                ],
                [
                    'name' => 'Tresses simples',
                    'price' => '40 €',
                ],
                [
                    'name' => 'Tresses motifs',
                    'price' => '50 €',
                ],
                [
                    'name' => 'Tresses rajout',
                    'price' => '70 €',
                ],
                [
                    'name' => 'Vanilles rajout',
                    'price' => '65 / 75 / 85 €',
                ],
                [
                    'name' => 'Nattes rajout',
                    'price' => '75 / 85 / 95 €',
                ],
                [
                    'name' => 'Locks invisibles',
                    'price' => '90 €',
                ],
                [
                    'name' => 'Coupe Homme / Femme',
                    'price' => '20 €',
                ],
                [
                    'name' => 'Coupe + Barbe',
                    'price' => '30 €',
                ],
                [
                    'name' => 'Coupe + Barbe + Épilation',
                    'price' => '35 €',
                ],
                [
                    'name' => 'Coupe enfant 0–10 ans',
                    'price' => '15 €',
                ],
                [
                    'name' => 'Coupe ado 11–17 ans',
                    'price' => '17 €',
                ],
                [
                    'name' => 'Coupe + Shampoing',
                    'price' => '25 €',
                ],
                [
                    'name' => 'Barbe',
                    'price' => '10 / 12 / 15 €',
                ],
                [
                    'name' => 'Contour + Barbe',
                    'price' => '15 €',
                ],
                [
                    'name' => 'Coupe + Wave',
                    'price' => '40 €',
                ],
                [
                    'name' => 'Motifs',
                    'price' => 'Dès 3 €',
                ],
                [
                    'name' => 'Coupe + Épilation',
                    'price' => '25 €',
                ],
                [
                    'name' => 'Épilation',
                    'price' => '8 €',
                ],
                [
                    'name' => 'Coiffage',
                    'price' => '3 €',
                ],
                [
                    'name' => 'Balayage',
                    'price' => '18 / 20 / 30 €',
                ],
                [
                    'name' => 'Shampoing Homme / Femme',
                    'price' => '8 €',
                ],
                [
                    'name' => 'Shampoing + Crème',
                    'price' => '16 €',
                ],
            ],
        ],
        [
            'title' => 'Soins & techniques',
            'items' => [
                [
                    'name' => 'Shampoing + Crème + Séchage',
                    'price' => '30 €',
                ],
                [
                    'name' => 'Déjaunisseur',
                    'price' => '20 €',
                ],
                [
                    'name' => 'Décoloration + Shampoing + Crème',
                    'price' => '30 / 35 / 40 €',
                ],
                [
                    'name' => 'Rinçage',
                    'price' => '25 €',
                ],
                [
                    'name' => 'Coloration permanente',
                    'price' => '30 €',
                ],
                [
                    'name' => 'Coloration ton sur ton',
                    'price' => '25 €',
                ],
                [
                    'name' => 'Soin adulte',
                    'price' => '45 €',
                ],
                [
                    'name' => 'Soin enfant',
                    'price' => '35 €',
                ],
                [
                    'name' => 'Mèche Homme',
                    'price' => '12 €',
                ],
                [
                    'name' => 'Shampoing + Coiffure simple enfant',
                    'price' => '35 €',
                ],
                [
                    'name' => 'Défaire une coiffure',
                    'price' => '20 €',
                ],
            ],
        ],
        [
            'title' => 'Locks',
            'items' => [
                [
                    'name' => 'Shampoing + Twist + Coiffure',
                    'price' => '65 / 70 / 80 €',
                ],
                [
                    'name' => 'Shampoing seul',
                    'price' => '30 / 40 / 50 €',
                ],
                [
                    'name' => 'Twist + Coiffure',
                    'price' => '50 / 60 / 70 €',
                ],
                [
                    'name' => 'Décapage + Twist + Coiffure',
                    'price' => '80 / 90 / 100 €',
                ],
                [
                    'name' => 'Soin + Twist + Coiffure',
                    'price' => '80 / 90 / 100 €',
                ],
                [
                    'name' => 'Soin',
                    'price' => '60 / 70 / 80 €',
                ],
                [
                    'name' => 'Twist',
                    'price' => '40 / 45 / 50 €',
                ],
                [
                    'name' => 'Coiffure',
                    'price' => '10 / 15 / 20 €',
                ],
                [
                    'name' => 'Vanilles / Nattes',
                    'price' => '15 / 20 / 25 €',
                ],
                [
                    'name' => 'Bain d’huile',
                    'price' => '15 / 20 / 25 €',
                ],
                [
                    'name' => 'Départ locks vanilles',
                    'price' => '45 / 50 / 55 €',
                ],
                [
                    'name' => 'Départ locks “keeneez”*',
                    'price' => '40 / 45 / 50 €',
                ],
                [
                    'name' => 'Départ locks instantané',
                    'price' => 'Dès 250 €',
                ],
                [
                    'name' => 'Micro locks avec mèches',
                    'price' => 'Dès 600 €',
                ],
            ],
        ],
    ],
    'price_variants_note' => 'Lorsque plusieurs prix sont indiqués (par exemple 65 / 75 / 85 €), le tarif dépend de la quantité de cheveux.',
    'prices_confirmed' => false,
    'prices_note' => 'Tarifs indicatifs : contactez le salon pour confirmer le prix de votre prestation.',
    'locks_note' => '* Libellé à confirmer auprès du salon.',
    'products_background' => [
        'src' => 'images/business/product-shelf.jpg',
    ],
    'products' => [
        [
            'name' => 'Almond & Avocado Curl Enhancing Mousse',
            'brand' => 'Design Essentials',
            'description' => 'Mousse coiffante à l’amande et à l’avocat pour dessiner les boucles.',
            'price' => 'Prix sur demande',
            'stock' => 'in_stock',
            'details' => 'La gamme Natural Hair Almond & Avocado associe amande et avocat dans cette mousse pour boucles. Le flacon pompe permet de distribuer la mousse.',
            'size' => '',
            'photo' => [
                'src' => 'images/products/design-essentials-almond-avocado-curl-enhancing-mousse.jpg',
                'alt' => 'Design Essentials — Almond & Avocado Curl Enhancing Mousse',
            ],
        ],
        [
            'name' => 'Almond & Avocado Honey Curl Forming Custard',
            'brand' => 'Design Essentials',
            'description' => 'Crème coiffante au miel pour la mise en forme des boucles.',
            'price' => 'Prix sur demande',
            'stock' => 'in_stock',
            'details' => 'Ce custard au miel fait partie de la gamme Almond & Avocado. Sa texture crème se présente en pot pour accompagner la mise en forme des boucles.',
            'size' => '354 g',
            'photo' => [
                'src' => 'images/products/design-essentials-almond-avocado-honey-curl-forming-custard.jpg',
                'alt' => 'Design Essentials — Almond & Avocado Honey Curl Forming Custard',
            ],
        ],
        [
            'name' => 'Almond & Avocado Sulfate-Free Shampoo',
            'brand' => 'Design Essentials',
            'description' => 'Shampoing sans sulfates, hydratant et démêlant, à l’amande et à l’avocat.',
            'price' => 'Prix sur demande',
            'stock' => 'in_stock',
            'details' => 'Ce shampoing de la gamme Almond & Avocado porte les mentions Moisturizing & Detangling et Sulfate-Free sur son flacon. Il réunit lavage, hydratation et démêlage dans la même étape.',
            'size' => '350 ml',
            'photo' => [
                'src' => 'images/products/design-essentials-almond-avocado-sulfate-free-shampoo.jpg',
                'alt' => 'Design Essentials — Almond & Avocado Sulfate-Free Shampoo',
            ],
        ],
        [
            'name' => 'Coconut & Monoi Curl Refresher',
            'brand' => 'Design Essentials',
            'description' => 'Brume à l’eau de coco pour rafraîchir les boucles entre les coiffages.',
            'price' => 'Prix sur demande',
            'stock' => 'in_stock',
            'details' => 'Ce spray de la gamme Coconut & Monoi est présenté en flacon vaporisateur. Il complète la routine des cheveux bouclés entre deux coiffages.',
            'size' => '',
            'photo' => [
                'src' => 'images/products/design-essentials-coconut-monoi-coconut-water-curl-refresher.jpg',
                'alt' => 'Design Essentials — Coconut & Monoi Curl Refresher',
            ],
        ],
        [
            'name' => 'Formations Finishing Spritz',
            'brand' => 'Design Essentials',
            'description' => 'Spray de finition pour fixer la coiffure.',
            'price' => 'Prix sur demande',
            'stock' => 'in_stock',
            'details' => 'Formations est un finishing spritz : un spray destiné à la finition de la coiffure. Présentation en flacon vaporisateur.',
            'size' => '237 ml',
            'photo' => [
                'src' => 'images/products/design-essentials-formations-finishing-spritz.jpg',
                'alt' => 'Design Essentials — Formations Finishing Spritz',
            ],
        ],
        [
            'name' => 'Almond & Avocado Curling Crème',
            'brand' => 'Design Essentials',
            'description' => 'Crème coiffante à l’amande et à l’avocat pour les cheveux bouclés.',
            'price' => 'Prix sur demande',
            'stock' => 'in_stock',
            'details' => 'Cette crème de la gamme Natural Hair Almond & Avocado est présentée en pot. Demandez conseil au salon pour choisir entre crème, mousse et custard selon votre coiffure.',
            'size' => '',
            'photo' => [
                'src' => 'images/products/design-essentials-natural-almond-avocado-curling-creme.jpg',
                'alt' => 'Design Essentials — Almond & Avocado Curling Crème',
            ],
        ],
        [
            'name' => 'Rosemary & Mint Conditioner — tube',
            'brand' => 'Design Essentials',
            'description' => 'Après-shampoing hydratant au romarin et à la menthe, présenté en tube.',
            'price' => 'Prix sur demande',
            'stock' => 'in_stock',
            'details' => 'Le soin porte le nom Rosemary & Mint Stimulating Super Moisturizing Conditioner. Cette fiche correspond au format tube ; le format pot possède sa propre fiche.',
            'size' => '170 g',
            'photo' => [
                'src' => 'images/products/design-essentials-rosemary-mint-moisturizing-conditioner.jpg',
                'alt' => 'Design Essentials — Rosemary & Mint Conditioner — tube',
            ],
        ],
        [
            'name' => 'Rosemary & Mint Conditioner — pot',
            'brand' => 'Design Essentials',
            'description' => 'Après-shampoing hydratant au romarin et à la menthe, présenté en pot.',
            'price' => 'Prix sur demande',
            'stock' => 'in_stock',
            'details' => 'Le soin porte le nom Rosemary & Mint Stimulating Super Moisturizing Conditioner. Cette fiche correspond au format pot ; le format tube possède sa propre fiche.',
            'size' => '',
            'photo' => [
                'src' => 'images/products/design-essentials-rosemary-mint-super-moisturizing-conditioner.jpg',
                'alt' => 'Design Essentials — Rosemary & Mint Conditioner — pot',
            ],
        ],
        [
            'name' => 'Keratin Hair Gel',
            'brand' => 'Gabri Professional',
            'description' => 'Gel coiffant à la kératine pour mettre en forme les cheveux.',
            'price' => 'Prix sur demande',
            'stock' => 'in_stock',
            'details' => 'Gel de la gamme professionnelle Gabri, portant la mention Keratin. Il est présenté en pot pour le coiffage des cheveux.',
            'size' => '250 ml',
            'photo' => [
                'src' => 'images/products/gabri-professional-keratin-hair-gel.jpg',
                'alt' => 'Gabri Professional — Keratin Hair Gel',
            ],
        ],
        [
            'name' => 'Natural Cologne — S1, S2 & S3',
            'brand' => 'Gabri Professional',
            'description' => 'Eaux de Cologne en petits flacons. Les trois variantes sont présentées sur la photo.',
            'price' => 'Prix sur demande',
            'stock' => 'in_stock',
            'details' => 'La photo réunit les variantes S1, S2 et S3 de Natural Cologne. Chaque flacon contient 75 ml. Le statut affiché concerne cette sélection ; précisez la variante souhaitée au salon.',
            'size' => '75 ml par flacon',
            'photo' => [
                'src' => 'images/products/gabri-professional-natural-cologne.jpg',
                'alt' => 'Gabri Professional — Natural Cologne — S1, S2 & S3',
            ],
        ],
        [
            'name' => '2-in-1 Beard Shampoo & Conditioner',
            'brand' => 'Gummy Professional',
            'description' => 'Shampoing et après-shampoing deux-en-un pour la barbe.',
            'price' => 'Prix sur demande',
            'stock' => 'in_stock',
            'details' => 'Ce soin de barbe réunit shampoing et après-shampoing. Le flacon pompe porte la mention Herbal Keratin de la gamme Gummy Professional.',
            'size' => '',
            'photo' => [
                'src' => 'images/products/gummy-professional-2-in-1-beard-shampoo-conditioner.jpg',
                'alt' => 'Gummy Professional — 2-in-1 Beard Shampoo & Conditioner',
            ],
        ],
        [
            'name' => 'Beard Oil — 50 ml',
            'brand' => 'Gummy Professional',
            'description' => 'Huile pour l’entretien quotidien de la barbe, en flacon de 50 ml.',
            'price' => 'Prix sur demande',
            'stock' => 'in_stock',
            'details' => 'Cette huile Gummy Professional est dédiée à la barbe. Elle est présentée en petit flacon avec son étui.',
            'size' => '50 ml',
            'photo' => [
                'src' => 'images/products/gummy-professional-beard-oil-50-ml.jpg',
                'alt' => 'Gummy Professional — Beard Oil — 50 ml',
            ],
        ],
        [
            'name' => 'Bump Repair',
            'brand' => 'Gummy Professional',
            'description' => 'Soin après-rasage de la gamme Gummy Professional.',
            'price' => 'Prix sur demande',
            'stock' => 'in_stock',
            'details' => 'Bump Repair complète la gamme de rasage Gummy Professional. Présenté en flacon avec son étui ; consultez les indications du fabricant pour son application.',
            'size' => '',
            'photo' => [
                'src' => 'images/products/gummy-professional-bump-repair.jpg',
                'alt' => 'Gummy Professional — Bump Repair',
            ],
        ],
        [
            'name' => 'Menthe — gel coiffant',
            'brand' => 'Hairgum',
            'description' => 'Gel coiffant à la menthe pour structurer la coiffure.',
            'price' => 'Prix sur demande',
            'stock' => 'in_stock',
            'details' => 'Ce gel de la gamme Hairgum Menthe est présenté en grand pot. Il fait partie des produits de coiffage proposés au salon.',
            'size' => '500 g',
            'photo' => [
                'src' => 'images/products/hairgum-menthe-styling-gel.jpg',
                'alt' => 'Hairgum — Menthe — gel coiffant',
            ],
        ],
        [
            'name' => 'Road Tiaré — baume coiffant',
            'brand' => 'Hairgum',
            'description' => 'Baume coiffant au tiaré, présenté en boîte métallique.',
            'price' => 'Prix sur demande',
            'stock' => 'in_stock',
            'details' => 'Road Tiaré est un baume coiffant Hairgum, présenté en boîte métallique. Son format se distingue des gels de la même marque.',
            'size' => '100 g',
            'photo' => [
                'src' => 'images/products/hairgum-road-tiare.jpg',
                'alt' => 'Hairgum — Road Tiaré — baume coiffant',
            ],
        ],
        [
            'name' => 'Baume Nourrissant Banane & Maracudja',
            'brand' => 'Iléa Cosmétiques',
            'description' => 'Baume capillaire nourrissant à la banane et au maracudja.',
            'price' => 'Prix sur demande',
            'stock' => 'in_stock',
            'details' => 'Ce baume Iléa Cosmétiques associe banane et maracudja. Il est présenté en pot dans la gamme de soins nourrissants de la marque.',
            'size' => '100 g',
            'photo' => [
                'src' => 'images/products/ilea-cosmetiques-baume-nourrissant-banane.jpg',
                'alt' => 'Iléa Cosmétiques — Baume Nourrissant Banane & Maracudja',
            ],
        ],
        [
            'name' => 'Co-wash Douceur Grenade & Avocat',
            'brand' => 'Iléa Cosmétiques',
            'description' => 'Soin lavant à la grenade et à l’avocat pour le lavage des cheveux.',
            'price' => 'Prix sur demande',
            'stock' => 'in_stock',
            'details' => 'Co-wash Douceur appartient à la gamme Grenade & Avocat de Iléa Cosmétiques. Ce soin lavant est présenté en flacon.',
            'size' => '250 ml',
            'photo' => [
                'src' => 'images/products/ilea-cosmetiques-co-wash-douceur-grenade-avocat.jpg',
                'alt' => 'Iléa Cosmétiques — Co-wash Douceur Grenade & Avocat',
            ],
        ],
        [
            'name' => 'Huile Elixir Banane & Maracudja',
            'brand' => 'Iléa Cosmétiques',
            'description' => 'Huile capillaire à la banane et au maracudja, en flacon pompe.',
            'price' => 'Prix sur demande',
            'stock' => 'in_stock',
            'details' => 'Cette huile appartient à la gamme Banane & Maracudja de Iléa Cosmétiques. Son flacon pompe accompagne les soins capillaires de la gamme.',
            'size' => '100 ml',
            'photo' => [
                'src' => 'images/products/ilea-cosmetiques-huile-elixir-banane-maracudja.jpg',
                'alt' => 'Iléa Cosmétiques — Huile Elixir Banane & Maracudja',
            ],
        ],
        [
            'name' => 'White Silver Shampoo',
            'brand' => 'Lakmé Teknia',
            'description' => 'Shampoing nuanceur pour cheveux blonds, méchés et blancs.',
            'price' => 'Prix sur demande',
            'stock' => 'in_stock',
            'details' => 'White Silver appartient à la gamme Teknia de Lakmé. Le flacon indique un shampoing nuanceur pour cheveux blonds, méchés et blancs.',
            'size' => '300 ml',
            'photo' => [
                'src' => 'images/products/lakme-teknia-white-silver-shampoo.jpg',
                'alt' => 'Lakmé Teknia — White Silver Shampoo',
            ],
        ],
        [
            'name' => 'Masque Douceur Grenade & Avocat',
            'brand' => 'Iléa Cosmétiques',
            'description' => 'Masque capillaire à la grenade et à l’avocat pour cheveux secs et ternes.',
            'price' => 'Prix sur demande',
            'stock' => 'in_stock',
            'details' => 'Ce masque Iléa Cosmétiques est présenté en pot dans la gamme Grenade & Avocat. Son étiquette le destine aux cheveux secs et ternes.',
            'size' => '250 g',
            'photo' => [
                'src' => 'images/products/masque-douceur-grenade-et-avocat.jpg',
                'alt' => 'Iléa Cosmétiques — Masque Douceur Grenade & Avocat',
            ],
        ],
        [
            'name' => 'Purple Styling Hair Color Wax',
            'brand' => 'Morfose',
            'description' => 'Cire coiffante colorante violette pour personnaliser la coiffure.',
            'price' => 'Prix sur demande',
            'stock' => 'in_stock',
            'details' => 'La teinte présentée est Purple, un violet. Cette Hair Color Wax Morfose combine produit de coiffage et couleur, en pot.',
            'size' => '100 ml',
            'photo' => [
                'src' => 'images/products/morfose-purple-styling-hair-colour-wax.jpg',
                'alt' => 'Morfose — Purple Styling Hair Color Wax',
            ],
        ],
        [
            'name' => 'Black Hair Styling Gel',
            'brand' => 'Rolda',
            'description' => 'Gel coiffant noir à fixation extra forte.',
            'price' => 'Prix sur demande',
            'stock' => 'in_stock',
            'details' => 'Le pot Black porte la mention Extra Strong Hold. Ce gel noir fait partie de la gamme de coiffage Rolda, aux côtés de Power et de la crème White.',
            'size' => '',
            'photo' => [
                'src' => 'images/products/rolda-black-hair-styling-gel.jpg',
                'alt' => 'Rolda — Black Hair Styling Gel',
            ],
        ],
        [
            'name' => 'Hair Molding Cream White',
            'brand' => 'Rolda',
            'description' => 'Crème coiffante à fixation extra forte pour sculpter les cheveux.',
            'price' => 'Prix sur demande',
            'stock' => 'in_stock',
            'details' => 'La variante White porte la mention Extra Strong Hold. Cette crème de modelage se distingue des gels Black et Power de Rolda.',
            'size' => '',
            'photo' => [
                'src' => 'images/products/rolda-hair-molding-cream-white.jpg',
                'alt' => 'Rolda — Hair Molding Cream White',
            ],
        ],
        [
            'name' => 'Power Hair Styling Gel',
            'brand' => 'Rolda',
            'description' => 'Gel coiffant de la gamme Power à fixation forte.',
            'price' => 'Prix sur demande',
            'stock' => 'in_stock',
            'details' => 'La variante Power porte la mention Mega Strong Hold. Elle est présentée en pot avec une étiquette orange dans la gamme Rolda.',
            'size' => '',
            'photo' => [
                'src' => 'images/products/rolda-power-hair-styling-gel.jpg',
                'alt' => 'Rolda — Power Hair Styling Gel',
            ],
        ],
        [
            'name' => 'Black Earth Products Strengthener',
            'brand' => 'Taliah Waajid',
            'description' => 'Soin capillaire au tea tree et à l’huile de coco.',
            'price' => 'Prix sur demande',
            'stock' => 'in_stock',
            'details' => 'Strengthener appartient à la gamme Black Earth Products de Taliah Waajid. Le pot indique la présence de tea tree et d’huile de coco.',
            'size' => '177 ml',
            'photo' => [
                'src' => 'images/products/taliah-waajid-black-earth-products-strengthener.jpg',
                'alt' => 'Taliah Waajid — Black Earth Products Strengthener',
            ],
        ],
        [
            'name' => '100% Pure Shea Butter',
            'brand' => 'Tropical Naturals',
            'description' => 'Beurre de karité pur sans parfum, présenté en pot.',
            'price' => 'Prix sur demande',
            'stock' => 'in_stock',
            'details' => 'Le pot Tropical Naturals porte les mentions 100% Pure Shea Butter et Fragrance Free. Il contient du beurre de karité sans parfum.',
            'size' => '',
            'photo' => [
                'src' => 'images/products/tropical-naturals-100-pure-shea-butter.jpg',
                'alt' => 'Tropical Naturals — 100% Pure Shea Butter',
            ],
        ],
        [
            'name' => 'Traitement au soufre',
            'brand' => 'Vioplantes',
            'description' => 'Soin au soufre pour le cuir chevelu. Demandez conseil au salon pour son utilisation.',
            'price' => 'Prix sur demande',
            'stock' => 'in_stock',
            'details' => 'Ce produit Vioplantes est présenté en pot sous le nom Traitement au soufre. Consultez les indications figurant sur le produit et demandez conseil au salon.',
            'size' => '',
            'photo' => [
                'src' => 'images/products/vioplantes-traitement-au-soufre.jpg',
                'alt' => 'Vioplantes — Traitement au soufre',
            ],
        ],
        [
            'name' => 'Huile de coco extra vierge',
            'brand' => 'Yona T',
            'description' => 'Huile de coco extra vierge, en flacon de 100 ml.',
            'price' => 'Prix sur demande',
            'stock' => 'in_stock',
            'details' => 'Le flacon Yona T porte la mention Huile de coco extra vierge. Il est présenté dans un format de 100 ml.',
            'size' => '100 ml',
            'photo' => [
                'src' => 'images/products/yona-t-extra-virgin-coconut-oil.jpg',
                'alt' => 'Yona T — Huile de coco extra vierge',
            ],
        ],
    ],
];
